### ISSUE TITLE
The InsertTableCommand should break paragraph where the selection is anchored

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-table#27]
As @oleq pointed out:

> Why is the table inserted after current block instead of splitting it (see v4 https://ckeditor.com/ckeditor-4/)? It's not very intuitive IMO.

![kapture 2018-05-30 at 13 29 45](https://user-images.githubusercontent.com/1099479/40717690-a2a165aa-640d-11e8-8e63-58cf934f5e13.gif)

**Comment by Reinmar** [comment]
That's not critical so I'm moving this out of iteration 18.

And as for expected result, please use `model.insertContent()` which will take care of handling situations like inserting this into an empty paragraph (should replace it) or into a block quote (should split `p` and `bQ`).

**Comment by Reinmar** [comment]
See: 

https://github.com/ckeditor/ckeditor5-image/blob/076591e7f3b2eda73d172d6dcbabf8de3972aeba/src/imageupload/imageuploadui.js#L49-L53

**Comment by pjasiun** [comment]
Yep, we had a long discussion if an image insertion should break a block and agreed it should not, see https://github.com/ckeditor/ckeditor5-image/blob/076591e7f3b2eda73d172d6dcbabf8de3972aeba/src/imageupload/utils.js#L24-L38

However, image and tables are not exactly the same case. For images, we had mostly image drop in mind. It is hard to select position precisely when you drop, what was an argument to prevent block split. An image can be also aligned to the side, to be an illustration of the paragraph. To do so, the image needs to be inserted before the block. This is why the image is usually inserted before the block (except the case when the selection is at the end of the block). 

In case of tables, I am not sure if they should break blocks. What I am sure, it that the table should be inserted before the block if the selection is at the beginning of the block. Otherwise, inserting tables using block toolbar will bring bad UX.

**Comment by pjasiun** [comment]
![insert-before-after](https://user-images.githubusercontent.com/1166967/45300977-1e76b380-b510-11e8-8890-82c9fa892c99.gif)

We added tables feature to Letters and now it is inconsistent that image is inserted before and table after the paragraph.

**Comment by pjasiun** [comment]
It is exceptionally bad when I insert into an empty paragraph: table feature leaves an empty paragraph instead of replacing it:

![insert-empty](https://user-images.githubusercontent.com/1166967/45301169-a9f04480-b510-11e8-8995-1f11318a4321.gif)

**Comment by Reinmar** [comment]
Just so you don't need to worry: `model.insertContent()` takes care of inserting into an empty paragraph.

> We added tables feature to Letters and now it is inconsistent that image is inserted before and table after the paragraph.

And for that we need to expose the `findOptimalInsertionPosition()` from image upload utils. I wonder... where should it end? Maybe it could become a part of `model.insertContent()` itself? An option maybe?

**Comment by Reinmar** [comment]
But let's continue this discussion in https://github.com/ckeditor/ckeditor5/issues/1243.
