### ISSUE TITLE
Support block content inside tables

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-table#56]
The [MVP](https://github.com/ckeditor/ckeditor5-table/issues/3) of the table feature doesn't contain a support for block content inside table cells. So, the first version will only support inline content (no images, no lists, no hard line breaks etc.)

Support for block content is our next priority after releasing the MVP. The challenge here is the UX. By default, we insert a table with inline content only:

```html
<table>
    <tr> 
       <td>Foo</td>
       <td>Boo</td>
   </tr>
</table>
```

When the user presses <kbd>Enter</kbd> in one of the cells, what should happen? We need to insert paragraphs there:

```html
<table>
    <tr> 
       <td><p>Foo</p><p>Bar</p></td>
       <td>Boo</td>
   </tr>
</table>
```

Is it ok that only one cell has block content and the other has inline content? This may cause vertical misalignment due to styling (paragraphs have margins) and general mess. So perhaps once you create block content in one of the cells, we should turn the entire table into "block table"?

There are also implementation issues. How to reflect that in the schema? A cell may contain inline content. Or it may contain block content. These are two different types of cells. Two different elements. Also, for features like headings, lists, etc. to be enabled, a block must be allowed in the current selection position. So, without paragraphs in the model all these features will be disabled. So, in fact, we always need paragraphs in the model.

And so on and so on :)

**Comment by jodator** [comment]
Quick test of:
```js
schema.extend( '$block', { allowIn: 'tableCell' } );
```
Kinda works (I didn't check for bugs long enough to find any):
![selection_022](https://user-images.githubusercontent.com/247363/43142218-2aeb7430-8f58-11e8-9b30-dd10d21632ce.png)

As you can see both types of content are allowed in `tableCell` so maybe it will work on single `tableCell` element :thinking:.

Some observations:

- <kbd>TAB</kbd> - ie for lists (AFAICS only last item can be intended with <kbd>TAB</kbd>.
- selection is a bit buggy IMHO - after trying to select next list item with <kbd>shift</kbd>+<kbd>right</kbd> the selection post-fixer selects whole table.
- (dunno if bug :stuck_out_tongue: ): table in table - will probably allow indifinte nesting but I don't insert `<p>`'s in tableCell on enter yet...
![selection_023](https://user-images.githubusercontent.com/247363/43142585-08dd5132-8f59-11e8-9569-1342a63e334a.png)
- you can remove paragraph from a table cell - so back to `$text` out of the box ;)

**Comment by pjasiun** [comment]
Does it works with collaboration?

**Comment by jodator** [comment]
@pjasiun kinda works (I didn't check for editing in the same time of a table though):

![peek 2018-07-24 16-14](https://user-images.githubusercontent.com/247363/43144153-ba444ffe-8f5c-11e8-8025-199ff347506a.gif)

**Comment by jodator** [comment]
OK time for some decisions to make as I've almost got this working:

![peek 2018-07-25](https://user-images.githubusercontent.com/247363/43196023-f4ee2b70-9006-11e8-8f25-b89e433b0832.gif)

@Reinmar / @pjasiun / @oleq :  Things to consider:

1. Does current behavior makes sense: wrap the table cell in `<paragraph>` and then execute `enter` command (for me not executing `enter` is not OK as it might lead to WTFs if "nothing changes" after one <kbd>enter</kbd> press.
2. Wrapping all table cells contents in `<paragraph>`s - YES / NO?
3. Should we disable this behavior when `paragraph` model is not available (kinda makes sense)?
4. Does current implementation in which we allow `$text` and `$block` inside `tableCell` is OK or do we need tow different elements like in @Reinmar's issue description?

ps.: Right now I have this thing working with some minor bugs with <kbd>tab</kbd>/<kbd>shift</kbd>+<kbd>tab</kbd> but this probably will be resolved quickly.

**Comment by jodator** [comment]
After some F2F talks:

1. We're going with always having `<paragraph>` inside `<tableCell>` in the model for empty cells and text-only cells. However it will be rendered differently for editng/data:
    - in the editing view: single `<paragraph>` will be rendered as `<span>` (if necessary), all other block (if single) or more then one `<paragraph>` will be rendered as in other places.
    - in the data pipeline: single `<paragraph`> will not be reneder (so it's `$text` will be placed directly into the `<td>` element.
This implies that in the view table will have mixed cells with and without `<p>` elements.
2. The <kbd>enter</kbd> will work as expected due to `<paragraph>` always present in the model.
3. The `Table` feature will not work without `Paragraph` properly but as for now we do not care as much - editor will throw error eventually.
4. Merging cells - will work as adding block elements so it should fix #38.
5. The <kbd>tab</kbd> should work for the lowest element so <kbd>tab</tab> in `<listItem>` will indent list.

**Comment by jodator** [comment]
@Reinmar & @pjasiun another thing...

What if `<paragraph>` has attribute like `alignment="right"` - I suppose that we should output the `<p>` even if such scenario:

```html
<table>
    <tableRow>
        <tableCell>
    </tableRow>
<table>
```

**Comment by Reinmar** [comment]
Yes... and no. I forgot about this but we discussed it on the first meeting. The problem here is that when you have a single block of content in a table cell then clicking the alignment buttons may also apply to the entire table cell... In fact, such option might also be useful even if there are multiple blocks. Unfortunately, as most non-semantical information, it can be applied pretty much everywhere and I can easily imagine people wanting to do all these things.

Let's extract this to a separate ticket because it may be a long and tiring discussion.

**Comment by oleq** [comment]
I guess we should fix the styles. OTOH:
* I'm not sure whether we should revert them to their original, left-aligned look&feel as they would stand out compared to the default (centered) table text,
  * OTTH I think it may be OK to align all block content to the left by default :P It's unlikely a table will mix an inline and block content and even if that's true, it's up to the developers to make sure this edge case goes well with their website,
* I'm not sure whether they should be fixed in the table content styles or feature (list, heading) content styles. The first option feels better because it will not bloat the editor styles when the tables feature is not loaded,

**Comment by jodator** [comment]
> It's unlikely a table will mix an inline and block content

I think that a table with one table cell with block contend and single paragraphs (inline content?) will already mix:

![selection_030](https://user-images.githubusercontent.com/247363/43631900-d1046ff8-9704-11e8-8292-0f287483f93a.png)


> I'm not sure whether they should be fixed in the table content styles or feature (list, heading) content styles.

A perfect solution would be conditionally loaded styles for integration purposes like `theme/table-paragraph.css` or `theme/table-list.css` but we do not have such mechanism :) So I'm for the first option - `table.css` should do this.

**Comment by wwalc** [comment]
> It's unlikely a table will mix an inline and block content

This is quite frequent use case. See for example:
* https://docs.ckeditor.com/ckeditor5/latest/builds/guides/migrate.html#configuration-options-compatibility-table
* https://sapui5.hana.ondemand.com/#/topic/74b59efa0eef48988d3b716bd0ecc933.html#loio74b59efa0eef48988d3b716bd0ecc933__table_hvl_wml_lx
 * http://www.oracle.com/us/products/system-requirements/release10/index.html

**Comment by jodator** [comment]
@oleq As #97 is almost ready: how to change table's content styles: should we revert to left alignment for table cells? Mixed? Follow up?

**Comment by Reinmar** [comment]
Ping, @oleq

**Comment by oleq** [comment]
> @oleq As #97 is almost ready: how to change table's content styles: should we revert to left alignment for table cells? Mixed? Follow up?

TBH I'm not sure I understand this question.

But I'd go with either: 
* `table.css` which makes the block content look like there was no table around (e.g. list items aligned to left instead of center). Unless we come up with some very smart table styles management system, leaving the whole "problem" to developers feels like a safe decision.
* table cell content aligned to the left by default. Then, there's no problem in the first place 😛 It's also the styling most of the WYSIWYG (and native too) editors implement out-of-the-box. 

I guess there's no good reason for CKE5 to stand out so I'd rather go with the later. It's simpler too and doesn't need maintanence as new content types arrive down the road. TBH, I don't quite remember why we went with centered table content in the first place (anyone?).

**Comment by Reinmar** [comment]
> table cell content aligned to the left by default. Then, there's no problem in the first place 😛 It's also the styling most of the WYSIWYG (and native too) editors implement out-of-the-box.

👍

**Comment by Reinmar** [comment]
We may perhaps consider whether headings should be centred or not. They will rarely contain block content and I *think* that it's frequent to centre them, but I don't know if it's worth potential problems and introducing such a difference in comparison to normal cells.

**Comment by jodator** [comment]
@Reinmar & @oleq to sum up and finish #97:

The styles of block contents inside a table will be as they are in other parts of the editor:
- `Paragraph`: left aligned
- `Heading`: left aligned
- `ListItem`: left aligned
